### ISSUE TITLE
some URIs that are returned from /object/meta should be pre url encoded

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/oni#7]
Reported by @SamHames when he was getting files from after we did the metadata migration most of the DOIs are encoded making an encoded decoded MESS

- We should decide whether we encode and when
- Why are DOIs IDs encoded and why are they needed
- Also the UI has to ramble against encoding decoding

**Comment by mraadgev** [comment]
DOIs are encoded because if they aren't we end up with the OCFL being additional levels deep, but we can revisit

**Comment by moisbo** [comment]
Hi @SamHames please check out fix we did. I deployed it in [data.ldaca.edu.au](https://data.ldaca.edu.au)
